import NavLink from "@/components/NavLink";
import Footer from "@/components/Footer";
import "@/styles/index.scss";


export const metadata = {
  title: "Alyse's 個人網站",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <NavLink />
        {children}
        <Footer />
      </body>
    </html>
  );
}
