import SocialIcons from '@/components/SocialIcons';

export const metadata = {
  title: '部落格',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <>
      {children}
      <section className="section-spacing d-none d-md-block">
        <div className="container">
          <div className="d-flex justify-content-between align-items-center">
            <p className="fs-2">alysewang@hexschool.com</p>
            <SocialIcons />
          </div>
        </div>
      </section>
    </>
  );
}
